// REDUX ACTION TYPES
export const AUTH_STATUS = "AUTH_STATUS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const CLEAR_GLOBAL_STATE = "CLEAR_GLOBAL_STATE";
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";

export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";
export const EMAIL_VERIFICATION_FAILURE = "EMAIL_VERIFICATION_FAILURE";

export const AUTH_RESET_PASSOWRD_SUCCESS = "AUTH_RESET_PASSOWRD_SUCCESS";
export const AUTH_RESET_PASSOWRD_FAILURE = "AUTH_RESET_PASSOWRD_FAILURE";

export const AUTH_SET_NEW_PASSOWRD_SUCCESS = "AUTH_SET_NEW_PASSOWRD_SUCCESS";
export const AUTH_SET_NEW_PASSOWRD_FAILURE = "AUTH_SET_NEW_PASSOWRD_FAILURE";

export const LOADING = "LOADING";

export const LOGOUT = "LOGOUT";
