export const AUTH_STATUS = "AUTH_STATUS";

export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS";
export const GET_EXAM_FAILURE = "GET_EXAM_FAILURE";

export const DELETE_EXAM_SUCCESS = "DELETE_EXAM_SUCCESS";
export const DELETE_EXAM_FAILURE = "DELETE_EXAM_FAILURE";

export const ADD_EXAM_SUCCESS = "ADD_EXAM_SUCCESS";
export const ADD_EXAM_FAILURE = "ADD_EXAM_FAILURE";

export const UPDATE_EXAM_SUCCESS = "UPDATE_EXAM_SUCCESS";
export const UPDATE_EXAM_FAILURE = "UPDATE_EXAM_FAILURE";

export const GET_BY_ID_EXAM_SUCCESS = "GET_EXAM_BY_ID_SUCCESS";
export const GET_BY_ID_EXAM_FAILURE = "GET_EXAM_BY_ID_FAILURE";

export const EXAM_LOADING = "EXAM_LOADING";
